version: '3'

services:
  web:
    build: .
    command: sh -c ". /opt/venv/bin/activate && uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    env_file:
    - .env.development
    ports:
      - 8000:8000
    volumes:
      - .:/app